services:
  - type: web
    name: task-manager-app
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://qodpovituewhzjmtvghh.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvZHBvdml0dWV3aHpqbXR2Z2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Nzg1MzQsImV4cCI6MjA3MzM1NDUzNH0.3bXYgN4WUgLWGq6KPST_gWxKxPdpK46RyrxGu_cEUF4
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        value: pk_test_Xm1QHZwiPtb4ixVJu5lVxKFF00pck52XVi

  - type: web
    name: task-manager-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NODE_ENV
        value: production
